### ISSUE TITLE
Add REST command interface

### ISSUE THREAD

**Issue by BeroSlingBlade** [Technolords/microservice-mock#10]
GET http://mockservice/mock/cmd?stop
to be able to stop the mockservice nicely. 

GET http://mockservice/mock/cmd?stats
to be able to display to stdout the current statistics (number of hits per matched request)

**Comment by BeroSlingBlade** [comment]
Maybe the rest DSL with restConfiguration on component "jetty" might be worth to take a look at.

**Comment by Technolords** [comment]
I've merged this into master, see PR: https://github.com/Technolords/microservice-mock/pull/14
Can you review/assert on the functionality? Note that the 'stats' and 'reset' commands will be implemented next (see https://github.com/Technolords/microservice-mock/issues/8).

**Comment by Technolords** [comment]
In favour of creating a release, closing this issue.
