### ISSUE TITLE
Add INFO loglevel

### ISSUE THREAD

**Issue by BeroSlingBlade** [Technolords/microservice-mock#12]
INFO loglevel should display epoch, uri, responsecode and elapsed time (first bit received until last bit sent) in parseable format.

Loglevel should be configurable by command interface (#10)

**Comment by Technolords** [comment]
After research, I've decided to change logging framework. This means I am moving away from logback to log4j 2. Reasons are:
- Performance: http://logging.apache.org/log4j/2.x/performance.html
- Better appenders: http://logging.apache.org/log4j/2.x/manual/appenders.html
- Better layouts: http://logging.apache.org/log4j/2.x/manual/layouts.html

**Comment by Technolords** [comment]
A PR is associated with this issue: https://github.com/Technolords/microservice-mock/pull/16

**Comment by Technolords** [comment]
In favour of creating a release, closing this issue.
