### ISSUE TITLE
Add dynamic query parameters to the URI

### ISSUE THREAD

**Issue by Sandilya1795** [Technolords/microservice-mock#46]
question on Microservice-mock
in the URI of Get or Post - can we make the parameters dynamic, so microservice responds accordingly to the mock request URI
something like this :
<configurations xmlns="http://xsd.technolords.net">

<configuration type="GET" url="/mock/admin/customerContext/v1.0/customerView/1287622">
<params>
<param>
<key>customerNumber</key>
<regex>/adsfasdf</regex>
</param>
<param>
<key>version</key>
<regex>/ads123f</regex>
</param>
</params>
<resource>customerView{customerNumber}{version}.json</resource>
</configuration>
</configurations>

**Comment by Technolords** [comment]
After exploring use cases, we came up with the following model:

```xml
<configuration type="GET" url="/mock/get">
    <query-groups>
        <query-group>
            <query-parameter key="key1">value1</query-parameter>
            <query-parameter key="key2">value2</query-parameter>
            <resource>mock/sample-get-complex.json</resource>
        </query-group>
        <query-group>
            <query-parameter key="customerNumber">{customerNumber}</query-parameter>
            <resource>mock/sample-get-{customerNumber}.json</resource>
        </query-group>
    </query-groups>
    <resource>mock/sample-get-default.json</resource>
</configuration>
```

**Comment by Technolords** [comment]
Partial implementation committed in branch: https://github.com/Technolords/microservice-mock/tree/issue/46

**Comment by Technolords** [comment]
See PR: https://github.com/Technolords/microservice-mock/pull/48
